basePath: http://103.84.192.244:8085/lw

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/livingword
    username: root
    password: GO816og#
    driver-class-name: com.mysql.jdbc.Driver
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    maxActive: 100
    minIdle: 10
    initialSize: 10
    removeAbandoned: true
    removeAbandonedTimeout: 60
    logAbandoned: true
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1

debug: true

file:
  location : /opt/apache-tomcat-8.5.39/webapps/images/

publicKey: /opt/public_key.der

