basePath: http://localhost:7000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/living_world
    username: alif
    password: katasandi
    driver-class-name: com.mysql.jdbc.Driver
debug: true

file:
  location: /Users/alif/workspace/icg/livingworld/backend/src/main/resources/files/

publicKey: /Users/alif/workspace/icg/livingworld/backend/public_key.der

