server:
  port: 7000
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  profiles:
    active: dev

jwt:
  secret: uk_gex1lmaqpg0ir5g1f5eftyaa1
  expiration: -1

resources:
   static-locations: file:src/mazin/resources/static/

eCash:
  username: livingworld
  password: pass123456
  url: https://api.mandiri-ecash.com/eCashHost
  apiKey: 56c4382d6873f46e7d000001959410aa05204e724cbd842ac3926b47
  urlWebRegister: http://188.166.220.62


pageSize : 10

iFabula:
  url: http://103.27.207.124/~ifabula/demo/apis/



